spring.application.name=spring-ai-rag
server.port=8000

# ========================================================================
# ollama
# ========================================================================
# Configuración general de Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.init.pull-model-strategy=when_missing

# Modelo para generación de texto / chat
spring.ai.ollama.chat.options.model=mistral

# Modelo específico para embeddings (Vectores)
spring.ai.ollama.embedding.options.model=nomic-embed-text

# Configuración de base de datos y vector store
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.datasource.url=jdbc:postgresql://localhost:5432/vectordb
spring.datasource.password=testpwd
spring.datasource.username=testuser